---
apiVersion: v1
kind: Service
metadata:
  name: spring-curioushead-root-project-service
  labels:
    app: spring-curioushead-root-project-app
spec:
  type: NodePort
  selector:
    app: spring-curioushead-root-project-app
  ports:
    - protocol: TCP
      port: 8091
      name: http
      nodePort: 30091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-curioushead-root-project
spec:
  selector:
    matchLabels:
      app: spring-curioushead-root-project-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-curioushead-root-project-app
    spec:
      containers:
        - name: spring-curioushead-root-project-container
          image: madhurm54/curioushead-projects:latest
          ports:
            - containerPort: 8091