---
apiVersion: v1
kind: Service
metadata:
  name: spring-api-service
  labels:
    app: spring-api-app
spec:
  type: NodePort
  selector:
    app: spring-api-app
  ports:
    - protocol: TCP
      port: 8090
      name: http
      nodePort: 30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
spec:
  selector:
    matchLabels:
      app: spring-api-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-api-app
    spec:
      containers:
        - name: spring-api-container
          image: madhurm54/api-docker:latest
          ports:
            - containerPort: 8090